name: CI/CD

on:
  push:
    branches: ["feature/teste-dakson"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      
      - name: Authentication Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
          
      - name: Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            dakson/job-test-backend:${{github.run_number}}
            dakson/job-test-backend:latest
       
  CD:
    runs-on: ubuntu-latest
    needs: [CI]

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v3.0
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.K8S_CONFIG}}
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v4.9
        with:
          images: dakson/job-test-backend:${{github.run_number}}
          manifests: |
            k8s/deployment.yaml

    
