name: Deploy to Azure Container Registry
on:
  push:
    branches:
      - feature/teste-dakson
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: daksoncontainer.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker-compose build
          docker-compose push
