name: Deploy to Azure Container Registry
on:
  push:
    branches:
      - feature/teste-dakson
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Log in to Azure Container Registry
        run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.ACR_ACCESS_TOKEN }} --tenant ${{ secrets.AZURE_TENANT_ID }}
      - name: Build and push Docker image
        run: |
          docker-compose build
          docker-compose push
