name: Build and deploy Dockerized Node.js app to Azure Web App - api-test-job

on:
  push:
    branches:
      - feature/teste-dakson
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker Image
      run: docker build -t daksoncontainer.azurecr.io/app:v1 .

    - name: Login to Azure Container Registry
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Docker Login to ACR
      run: |
          az acr login --name daksoncontainer
        
    - name: Docker push Image
      run: docker push daksoncontainer.azurecr.io/app:v1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'dev'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: docker-image

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'api-test-job'
          slot-name: 'dev'
          images: daksoncontainer.azurecr.io/app
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_af0d7127f1fb435fabb9adc926dfc29f }}
